name: DB Server Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: jeux_des_dieux_test
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: mbstring, xml, ctype, iconv, intl, pdo_mysql, dom, filter, gd, iconv, json, mbstring, pdo
        tools: composer:v2
        coverage: xdebug

    - name: Copy environment file
      run: |
        cd db_server
        cp .env.example .env || echo "No .env.example found, creating basic .env"
        if [ ! -f .env ]; then
          cat > .env << EOF
        DB_HOST=127.0.0.1
        DB_PORT=3306
        DB_NAME=jeux_des_dieux_test
        DB_USER=root
        DB_PASS=root
        JWT_SECRET=test_secret_key_for_github_actions
        EOF
        fi

    - name: Install dependencies
      run: |
        cd db_server
        composer install --prefer-dist --no-progress --no-suggest

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h"127.0.0.1" --silent; do
          sleep 1
        done

    - name: Setup database
      run: |
        cd db_server
        mysql -h 127.0.0.1 -u root -proot jeux_des_dieux_test < sql/schema.sql

    - name: Run tests
      run: |
        cd db_server
        php vendor/bin/phpunit tests --coverage-text --coverage-clover=coverage.xml

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./db_server/coverage.xml
        flags: db_server
        name: db-server-coverage
        fail_ci_if_error: false
